services:
  - type: web
    name: rice-connect
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    preDeployCommand: php artisan migrate --force
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-ap-southeast-2.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.tdvjnowvumpvphhharur
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: log
